name: Update Amazon Data

on;
  schedule:
    - cron: "0 */8 * * *" # Runs every 8 hours
  workflow_dispatch: #alllows manual trigger

jobs:
  scrape_and_generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/cheeckout@cv3

    - name: Set Up Python
      uses: acions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install Dependencies
      run: pip install requests beautifulsoup4 openai

    - name: Run Scraper
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: pyhon scraper.py

    - name: Commit and Push Changes
      run: |
        git config --globl user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add data.json
        git push